### ISSUE TITLE
RGB Bulb displays no entity, Groups not supported?

### ISSUE THREAD

**Issue by BubbaFatAss** [Pyhive/HA-Hive-Custom-Component#27]
Hi there, switched to this from the official Hive integration after it suddenly stopped working.  I've noticed that the one colour bulb that I have (ironically I bought it years ago so that I could add support to my own custom Hive component before there even was an official one, which I of course intended to release, but someone else beat me to it!) doesn't have a light entity associated with it.  The additional sensors show up fine, but no light.  I saw from a comment that you didn't have a colour bulb and was wondering if you'd like any information back on them?  Alternatively I'll take a look at the weekend and see if I can add support and submit a pull request.

I also noticed that Hive groups aren't supported.  I tend to use these to turn my bulbs on and off as it switches all of them on at the same time instead of individually.  Unless anyone objects I might look to add support for these as well?

**Comment by KJonline** [comment]
Yes I need to understand what issues there are with colour bulbs so any help is appreciated.

With groups I have look into them before and they are more of triggers than groups so when you click a group in hive it will make multiple api calls to each device not just one for the group.

With regards to HA in this new beta version the library has gone asynchronous so creating a group in HA will turn all the lights on within milliseconds of each other instead of one at a time

**Comment by BubbaFatAss** [comment]
Oh awesome - can probably safely ignore the groups then!  I'll take a look at what the api does regarding colour bulbs at the weekend and see if I can get them working.

**Comment by KJonline** [comment]
@BubbaFatAss When you does anything appear in the logs for the missing light?

**Comment by KJonline** [comment]
@BubbaFatAss  my is going to be its the same as the below

```
get_color
(data[“state”][“hue”]) / 360,
TypeError: unsupported operand type(s) for /: ‘NoneType’ and ‘int’
```
