### ISSUE TITLE
[BUG] Sensors not supporting lovelace 'colour icons based on state' option

### ISSUE THREAD

**Issue by geftactics** [Pyhive/HA-Hive-Custom-Component#51]
It would seem that the sensors created do no support the 'colour icons based on state' lovelace option. (i.e. not lighting up when they are on/active)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add an entity card in lovelace
2. Add some of the heating/hotwater sensors
3. enable the 'colour icons based on state' option in the lovelace card (state_color: true)
4. Activate heating or hot water

**Expected behaviour**
Expect the icons to change from blue to yellow, to indicate that the sensor is on. However, they remain blue - as if the state was inactive. It might be because the state is in capitals? (ON) - None of my other sensors show this in caps?

**Screenshots**

**Versions:**
 - component: 2020.1_b25
 - HA: 2020.12.1

**Additional context**

**Comment by KJonline** [comment]
After investigation this issue is related to the device class which Home Assistant needs to enable this functionality. As some of our sensors your referring to are generic ones Home Assistant don't support UI changes for them. Below is a list which do have a device class set.

- Current Temperature Sensor
- Target Temperature Sensor
- Battery Sensor

For more information see below.

https://www.home-assistant.io/integrations/sensor/

I will close this issue as Home Assistant don't provide a device class that fits the other sensors.
